import Head from 'next/head'
import Image from 'next/image'

import About from '../components/About'
import Hero from '../components/Hero'
import Projects from '../components/Projects'
import styles from '../styles/Home.module.css'
import Contact from '../components/Contact'

export default function Home() {
  return (
    <div className='p-4'>
      <Head>
        <title>Daniel&apos;s Portfolio</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Hero />
      <Projects />
      <About />
      <Contact />
    </div>
  )
}
